### ISSUE TITLE
Custom user suit palettes are not being read

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Community-Updates#42]
**Describe the bug**
Custom User Suit Palettes are not being read.

**To Reproduce**
Edit any of the suits and then boot the game.

**Expected behavior**
My custom user palette should being used, instead of the default colours.

**Platform (please complete the following information):**
 - OS: Windows / Linux
 - Version: 10 / Arch

**Game Version:**
1.5.2

**Comment by Lojemiru** [comment]
Issue resolved: user was not editing palette files as directed in explanation files.
