### ISSUE TITLE
Keyboard Input mapping is weird

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Community-Updates#54]
**Describe the bug**
You can map i.e the Super key, F9 to any buttons, which will cause very strange behaviour. If you map alt gr, it shows up as alt, but still expects alt gr

**To Reproduce**
See above

**Expected behavior**
Either the key's shouldn't be possible to mapped at all, or also exlpained above

**Platform (please complete the following information):**
 - OS: Windows, Linux
 - Version: 10, Arch

**Game Version:**
1.5.2

**Comment by Lojemiru** [comment]
Postponed for 2.0 controller input reworks - a key blacklist sounds like an excellent idea, but is not an immediate concern and would fit better with related changes in 2.0.
