### ISSUE TITLE
Add a toggle for AM2R to pause and/or don't accept input when it's not in focus

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Community-Updates#56]
**Describe the solution you'd like**
I would like a toggleable option, that allows you to pause AM2R and/or don't accept any input when it isn't in focus

**Comment by Lojemiru** [comment]
If possible in GM:S, this sounds like a nice eventual QoL change but is not a priority for 1.5.x builds. Postponed for review during 2.0 development.
