### ISSUE TITLE
Keep the Varia Cutscene skip

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Community-Updates#60]
**Is your feature request related to a problem? Please describe.**
It's really fun for routing, and the 10 second timesave is a nice reward for getting Gravity before Varia. It's not gamebreaking, and casual users wouldn't see this anyway.

**Comment by Lojemiru** [comment]
Interesting/esoteric speedrun tech like zips and OOB will be retained, but this seems like a common enough occurrence for players to run into that it should be fixed in the interest of overall polish.
