### ISSUE TITLE
Image is cut off on slight resizing

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Community-Updates#67]
**Describe the bug**
If the window is just slightly resized, then the image will be cut off. Happens on both widescreen and 4:3.

**To Reproduce**
Resize the window a bit.

**Expected behavior**
Since the full image cannot be displayed anymore, it should be scaled down + black bars.

**Media**
![grafik](https://user-images.githubusercontent.com/38186597/108242842-ae8f9d00-714d-11eb-8a8e-ae7273d10984.png)

**Platform (please complete the following information):**
 - OS: Windows, Linux
 - Version: 10, Arch

**Game Version:**
1.5.2

**Comment by Lojemiru** [comment]
Unless immediately game/experience-breaking, display bugs are postponed for 2.0's rework of the display manager.
